version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: restaurant_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-password}@db:5432/restaurant_tracker?sslmode=disable
      PORT: 3001
      NODE_ENV: production
      FRONTEND_URL: ${FRONTEND_URL:-https://pastel.mauriciocardozo.me}
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: